# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Clone the Node.js API repository from a Git repository
RUN git clone git@github.com:KevinFernandoNT/docker-git-clone.git .

# Install project dependencies
RUN npm install

# Expose the API port
EXPOSE 3000

# Set up a volume for the host machine to access the cloned repository
VOLUME [ "/app" ]

# Define the command to start the Node.js API
CMD ["npm", "start"]
